bootstrap:
  example:
    config: yaml
    log: logrus
    string: foo
    int: 123
    float: 3.14
    bool: true
  redis:
    cluster:
      addrs:
        - "127.0.0.1:7000"
        - "127.0.0.1:7001"
        - "127.0.0.1:7002"
        - "127.0.0.1:7003"
        - "127.0.0.1:7004"
        - "127.0.0.1:7005"